services:
  postgres:
    ports: []

  redis:
    ports: []

  minio:
    ports: []
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_SERVER_URL: https://s3.stgy.jp

  smtp:
    ports: []
    expose:
      - "8025"

  backend:
    ports: []

  frontend:
    ports: []

  caddy:
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile.vps:/etc/caddy/Caddyfile:ro
