services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${FAKEBOOK_DATABASE_USER}
      POSTGRES_PASSWORD: ${FAKEBOOK_DATABASE_PASSWORD}
      POSTGRES_DB: ${FAKEBOOK_DATABASE_NAME}
    ports:
      - "${FAKEBOOK_DATABASE_PORT}:${FAKEBOOK_DATABASE_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    restart: always
    ports:
      - "${FAKEBOOK_REDIS_PORT}:${FAKEBOOK_REDIS_PORT}"
    command: ["redis-server", "--requirepass", "${FAKEBOOK_REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    depends_on:
      - db
      - redis
    ports:
      - "${FAKEBOOK_BACKEND_PORT}:${FAKEBOOK_BACKEND_PORT}"
    environment:
      - FAKEBOOK_DATABASE_HOST=${FAKEBOOK_DATABASE_HOST}
      - FAKEBOOK_DATABASE_USER=${FAKEBOOK_DATABASE_USER}
      - FAKEBOOK_DATABASE_PASSWORD=${FAKEBOOK_DATABASE_PASSWORD}
      - FAKEBOOK_DATABASE_NAME=${FAKEBOOK_DATABASE_NAME}
      - FAKEBOOK_DATABASE_PORT=${FAKEBOOK_DATABASE_PORT}
      - FAKEBOOK_CHOKIDAR_USEPOLLING=${FAKEBOOK_CHOKIDAR_USEPOLLING}
      - FAKEBOOK_REDIS_HOST=${FAKEBOOK_REDIS_HOST}
      - FAKEBOOK_REDIS_PORT=${FAKEBOOK_REDIS_PORT}
      - FAKEBOOK_REDIS_PASSWORD=${FAKEBOOK_REDIS_PASSWORD}
      - FAKEBOOK_BACKEND_PORT=${FAKEBOOK_BACKEND_PORT}
    volumes:
      - ./backend:/app
    command: npm run dev

volumes:
  db_data:
  redis_data:
